### ISSUE TITLE
Gradle compatiblity

### ISSUE THREAD

**Issue by jtjeferreira** [Fadelis/protoc-gen-java-optional#1]
Hi! 

I wanted to try your plugin in my project but I am using gradle. I think due to this [issue](https://github.com/google/protobuf-gradle-plugin/issues/455) that is not possible. 
While that ticket is not solved the only workaround is to declare the mainclass in the manifest and publish a new version...

I will try to do this locally first to see if it works, and later try to do a PR (if my skills allow it)

**Comment by Fadelis** [comment]
Haven't tested it with `gradle`, but it worked with maven even with that typo. Thanks for the contribution, should be available with `1.6.0` version.
