### ISSUE TITLE
optional is not working, it doesn't allow me to set a field to null

### ISSUE THREAD

**Issue by yingshaoxo** [Fadelis/protoc-gen-java-optional#5]
https://github.com/grpc/grpc-java/issues/9868?notification_referrer_id=NT_kwDOAQZPrbM1NDkwMjk4NjY0OjE3MTkwODI5#issuecomment-1414495740

**Comment by Fadelis** [comment]
Hi @yingshaoxo , this is not related to this plugin extension, not sure why you'd open an issue here.
