### ISSUE TITLE
Insertion point not found

### ISSUE THREAD

**Issue by jimmyzzxhlh** [Fadelis/protoc-gen-java-optional#9]
Hi,

I looked around solutions for allowing nulls being passed into protobuf `set()` functions and this one looks really promising. Thank you for creating the plugin! 

I tried to integrate the plugin with my Gradle Java project, and here is how it looks like in `build.gradle.kts` (only left the related ones):

```
import com.google.protobuf.gradle.id

plugins {
    java
    id("com.google.protobuf") version "0.9.4"
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        proto {
            srcDir("../protobuf/helloworld")
        }
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.3"
    }

    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:1.62.2"
        }
        id("java_optional") {
            artifact = "org.grpcmock:protoc-gen-java-optional:1.10.0"
        }
    }

    generateProtoTasks {
        all().forEach { task ->
            task.plugins {
                id("grpc")
                id("java_optional")
            }
        }
    }
}

dependencies {
    compileOnly("io.grpc:protoc-gen-grpc-java:1.62.2")
    compileOnly("io.grpc:grpc-protobuf:1.62.2")
    compileOnly("io.grpc:grpc-stub:1.62.2")
    compileOnly("org.grpcmock:protoc-gen-java-optional:1.10.0")

    ...
}


```

Here is the hello world proto file, where I want the fields to be optional by using `google.protobuf.StringValue`. 

```
syntax = "proto3";
option java_package = "com.example.helloworld.protobuf";
option java_multiple_files = true;

import "google/protobuf/wrappers.proto";

package helloworld;

message HelloRequest {
  google.protobuf.StringValue name = 1;
}

message HelloReply {
  google.protobuf.StringValue message = 1;
}

```

However, when I run the gradle `generateProto` task, I got the following error:

```
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: com/example/helloworld/protobuf/HelloRequest.java: Tried to insert into file that doesn't exist.
  com/example/helloworld/protobuf/HelloRequest.java: insertion point "class_scope:helloworld.HelloRequest" not found.
  com/example/helloworld/protobuf/HelloReply.java: Tried to insert into file that doesn't exist.
  com/example/helloworld/protobuf/HelloReply.java: insertion point "class_scope:helloworld.HelloReply" not found.
```

Note that this only happens when I specify `google.protobuf.StringValue` as the type for the field. If I change it to `string` then the classes will be generated (obviously without getting any code generated from this plugin). 

I think I'm probably doing something wrong here and so would appreciate any help. Thank you!

**Comment by Fadelis** [comment]
Hi, I haven't tried running this plugin within some gradle generator plugin, but this protoc plugin needs to be run at the same time as the java output, if these are run separately then it will fail. If the gradle generator plugin doesn't support it then it won't be usable with it.

**Comment by jimmyzzxhlh** [comment]
@Fadelis Thanks for the response. This gave me some hint that I need to add `outputSubDir` as below to make it work.

```
    generateProtoTasks {
        all().forEach { task ->
            task.plugins {
                id("grpc")
                id("java_optional") {
                    outputSubDir = "java"
                }
            }
        }
    }
```

However, now that I'm looking at the generated code, e.g. for `HelloReply` class:

```
    public Builder setOrClearMessage(com.google.protobuf.StringValue value) {
      if (value != null) {
        return setMessage(value);
      } else {
        clearMessage();
      }
      return this;
    }
```

It doesn't seem to be that useful because the function is accepting a `StringValue` object instead of a `String` object. 

Most of the time I would start with an object with Java type (e.g. `String`), which can be null. Right now, with Protobuf I have to do the following (e.g. for pulling data from a database and then wrapping data using Protobuf):

```
    ExampleProtobufMessage.Builder builder = ExampleProtobufMessage.newBuilder();
    // resultSet is from JDBC after querying the database.
    // "id" and "name" are column names.
    Optional
        .ofNullable(resultSet.getObject("id"))  
        .ifPresent(value -> builder.setId(Int64Value.of(value)));
    Optional
        .ofNullable(resultSet.getObject("name"))  
        .ifPresent(value -> builder.setName(StringValue.of(value)));
```

What I would expect is to do something like:

```
ExampleProtobufMessage.Builder builder = ExampleProtobufMessage.newBuilder()
    .setOrClearId(resultSet.getObject("id"))  // This has to be getObject because getLong() will return a primitive long value
    .setOrClearName(resultSet.getObject("name"))
    ...
    .build();
```

So Ideally the `setOrClear()` function will have an implementation like:

```
    public Builder setOrClearId(Object value) {
      if (value != null) {
        // We can assert the type of the object to make sure it's a long.
        return setId(Int64Value.of((long)value)); 
      }
      else {
        clearId();
      }
      return this;
    }
```

For comparison, here is the current implementation of `setOrClearId()`:

```
    public Builder setOrClearId(com.google.protobuf.Int64Value value) {
      if (value != null) {
        return setId(value);
      } else {
        clearId();
      }
      return this;
    }
```

**Comment by Fadelis** [comment]
No sure why you'd expected for it to have different method signature than the original generated method. You can do if you want 
```java
builder.setId(Optional.ofNullable(esultSet.getObject("id")).map(Int64Value::of).orElse(null))
```
But these primitive wrappers were initially made for primitive types to be able to have field presence concept (have nullability on the wire), but since protoc 3.15 there's a new `optional` keyword for `proto3` version which is much more suited for it and adds possibility for field presence for primitive types.

**Comment by jimmyzzxhlh** [comment]
> No sure why you'd expected for it to have different method signature than the original generated method. You can do if you want
> 
> ```java
> builder.setId(Optional.ofNullable(esultSet.getObject("id")).map(Int64Value::of).orElse(null))
> ```
> 
> But these primitive wrappers were initially made for primitive types to be able to have field presence concept (have nullability on the wire), but since protoc 3.15 there's a new `optional` keyword for `proto3` version which is much more suited for it and adds possibility for field presence for primitive types.

You are right about the alternative (and it allows chaining as well). The only thing is that it's much more verbose than what I'm expecting :)
